### ISSUE TITLE
Getting error while buildingthrough mvn as the jar is not found in cloudera repo

### ISSUE THREAD

**Issue by rroyhere** [mraad/spark-dbf#3]
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find com.esri:Shapefile:jar:1.3.1 in https://repository.cloudera.com/artifactory/cloudera-repos was cached in the local repository, resolution will not be reattempted until the update interval of cloudera-releases has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)

**Comment by mraad** [comment]
Make sure to first clone, build and install https://github.com/mraad/Shapefile
